server:
  port: 8080

spring:
  application:
    name: shieldflow-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:shieldflow;DB_CLOSE_DELAY=-1}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
